[workspace]
members = [
    "crates/kreuzberg",
    "crates/kreuzberg-py",
    "crates/kreuzberg-ffi",
    "packages/ruby/ext/kreuzberg_rb/native",
    "crates/kreuzberg-cli",
    "crates/kreuzberg-node",
    "tools/benchmark-harness",
    "tools/e2e-generator",
    "e2e/rust",
]
default-members = [
    "crates/kreuzberg",
    "crates/kreuzberg-cli",
]
resolver = "2"

[patch.crates-io]
kreuzberg = { path = "crates/kreuzberg" }
rb-sys = { git = "https://github.com/oxidize-rb/rb-sys", rev = "acca8a7feac415f41f3773a940cbee2ae3167b94" }

[workspace.package]
version = "4.0.0-rc.1"
edition = "2024"
rust-version = "1.85"
authors = ["Na'aman Hirschfeld <nhirschfeld@gmail.com>"]
license = "MIT"
repository = "https://github.com/Goldziher/kreuzberg"
homepage = "https://kreuzberg.dev"

[workspace.dependencies]
serde_json = "1.0"
serde = "1.0"

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3
strip = true

[profile.dev]
opt-level = 0
debug = true
